name: Matrix

on:
  push:
    branches: [ main ]

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"accounts\":[10, 12, 14]}"
