name: Matrix

on:
  push:
    branches: [ main ]

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: set-matrix
        run: echo "::set-output name=accounts::[10, 12, 14]"


  matrix2:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
			# This needs to match the first job's name and output parameter
      matrix: 
        accounts: ${{fromJSON(needs.matrix.outputs.accounts)}}
    steps:
      - run: echo "${{ matrix.account }}"
