name: Matrix

on:
  push:
    branches: [ main ]

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: set-matrix
        run: echo "::set-output name=matrix::[10, 12, 14]"
      - uses: chiefus/gh-actions-matrix/.github/workflows/target.yml@main
        with: 
          accounts: ${{ steps.meta.outputs.matrix }}
