name: Matrix

on:
  push:
    branches: [ main ]

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      matrix: ${{ steps.set-matrix.outputs.accounts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: set-matrix
        run: echo "::set-output name=accounts::{\"accounts\":[10, 12, 14]}"


  matrix2:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.matrix.outputs.accounts)}}
    steps:
      - run: echo "${{ matrix.accounts }}"
