name: Matrix

on:
  push:
    branches: [ main ]

jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      ACCOUNTS: ${{ steps.set-accounts.outputs.ACCOUNTS }}
      FILES: ${{ steps.set-files.outputs.FILES }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: set-files
       # run: echo "::set-output name=accounts::{\"accounts\":[10, 12, 14]}"
        run: echo "FILES=file1 file2 file3" >> $GITHUB_OUTPUT
      - id: set-accounts
       # run: echo "::set-output name=accounts::{\"accounts\":[10, 12, 14]}"
        run: echo "ACCOUNTS={\"accounts\":[10, 12, 14]}" >> $GITHUB_OUTPUT


  matrix2:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.matrix.outputs.ACCOUNTS)}}
    steps:
      - run: echo "${{ matrix.accounts }}"

  matrix3:
    needs: matrix2
    runs-on: ubuntu-latest
    steps:
      - run: |
          for i in $(echo )echo "${{ needs.matrix.outputs.FILES }}"
          do
            echo $i
          done
