name: Cleaner

on:
  workflow_call:
    inputs:
      accounts:
        required: true
        type: string


jobs:
  account:
    strategy:
      matrix: 
        account: ${{fromJSON(inputs.accounts)}}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ matrix.account }}
